CREATE TABLE MASCOTAS (
  MASCOTA_ID INT PRIMARY KEY AUTO_INCREMENT,
  MASCOTA_NAME VARCHAR(255) NOT NULL,
  CLINICA_ID INT NOT NULL,
  LOCATION_ID INT
);

INSERT INTO MASCOTAS (MASCOTA_NAME, CLINICA_ID, LOCATION_ID) VALUES ('PONGO', 3, 4);
INSERT INTO MASCOTAS (MASCOTA_NAME, CLINICA_ID, LOCATION_ID) VALUES ('ROCKY', 2, 4);